# Generated by Django 2.0.2 on 2018-05-05 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='bikes', verbose_name="Product's image")),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="bike's name")),
                ('model', models.CharField(max_length=10, verbose_name='model number')),
                ('price', models.CharField(max_length=10, verbose_name='price')),
                ('size', models.CharField(max_length=5, verbose_name='frame size')),
                ('brand', models.CharField(max_length=30, verbose_name='brand')),
                ('description', models.TextField(verbose_name='description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory', verbose_name='category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'verbose_name': 'Bike',
            },
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.Products', verbose_name="Product's name"),
        ),
    ]
