# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="bike's name")),
                ('model', models.CharField(max_length=10, verbose_name='model number')),
                ('price', models.CharField(max_length=10, verbose_name='price')),
                ('size', models.CharField(max_length=5, verbose_name='frame size')),
                ('biketype', models.CharField(max_length=30, verbose_name='bike type')),
                ('brand', models.CharField(max_length=30, verbose_name='brand')),
                ('description', models.TextField(verbose_name='description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.BikeCategory', verbose_name='category')),
            ],
            options={
                'verbose_name_plural': 'Bikes',
                'verbose_name': 'Bike',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/bikes', verbose_name="Bike's image")),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Bikes', verbose_name="Bike's name")),
            ],
        ),
    ]
