# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True, verbose_name=b'Category name')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'', verbose_name=b"Bike's image")),
            ],
        ),
        migrations.RemoveField(
            model_name='bikes',
            name=b'name',
        ),
        migrations.AddField(
            model_name='bikes',
            name='bike_name',
            field=models.CharField(default=1, max_length=30, verbose_name=b"Bike's name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='bike_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Bikes', verbose_name=b"Bike's name"),
        ),
        migrations.AddField(
            model_name='bikes',
            name='category',
            field=models.OneToOneField(default='Mountain', on_delete=django.db.models.deletion.CASCADE, to='products.BikeCategory', to_field=b'category'),
            preserve_default=False,
        ),
    ]
