# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikes',
            name='biketype',
        ),
        migrations.RemoveField(
            model_name='images',
            name='bike',
        ),
        migrations.AddField(
            model_name='bikes',
            name='images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Images', verbose_name='Images'),
            preserve_default=False,
        ),
    ]
