# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180425_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Images', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(null=True, upload_to='bikes', verbose_name="Bike's image"),
        ),
    ]
