# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180425_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikes',
            name='images',
        ),
        migrations.AddField(
            model_name='bikes',
            name='images',
            field=models.ManyToManyField(null=True, to='products.Images', verbose_name='Images'),
        ),
    ]
